In [18]:
#veri algoritma için hazırlıycaz bu yönt hizli
transactions=[[str(u) for u in sepet if str(u) !='nan'] for sepet in df.values]
#kontrol için ilk sepeti yazdıralım
print(transactions[0])

['shrimp', 'almonds', 'avocado', 'vegetables mix', 'green grapes', 'whole weat flour', 'yams', 'cottage cheese', 'energy drink', 'tomato juice', 'low fat yogurt', 'green tea', 'honey', 'salad', 'mineral water', 'salmon', 'antioxydant juice', 'frozen smoothie', 'spinach', 'olive oil']

In [12]:
#sütün isimleri 0,1,2 oldoğu için sql de "0" nolu sütundaki ürünleri sayalım 
sorgu=""" select "0" as urun,count("0") as satis_adedi
from sepetler 
group by "0"
order by satis_adedi desc
limit 10
"""
populer_urunler=pd.read_sql_query(sorgu,conn)
populer_urunler

                urun  satis_adedi
0      mineral water          577
1            burgers          576
2             turkey          458
3          chocolate          391
4  frozen vegetables          373
5          spaghetti          354
6             shrimp          325
7      grated cheese          293
8               eggs          279
9            cookies          270

In [ ]:
sorgu="select * from sepetler limit5" 
sql_df=pd.read_sql_query(sorgu,conn)
sql_df

,index,0,1,2,3,4,5,6,7,8,...,10,11,12,13,14,15,16,17,18,19
0,0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,...,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7496,7496,butter,light mayo,fresh bread,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7497,7497,burgers,frozen vegetables,eggs,french fries,magazines,green tea,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7498,7498,chicken,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7499,7499,escalope,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7500,7500,eggs,frozen smoothie,yogurt cake,low fat yogurt,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
#veriyi okumak için .bu veri setinde başlık(header) olmadığı için None diyoruz.
df=pd.read_csv('Market_Basket_Optimisation.csv',header=None)
#ilk 5 satıra bakalım
df.head()
df.shape
#1.veri tabanıma bağlanalım(dosya yoksa otomatık oluşturur)
conn=sqlite3.connect('market_analizi.db')
#2. veriyi sql tablosuna aktaralım
#sepetler tablo adımız olucaz.
#index=true diyerek satır numaralarınıda (sepet ID gibi)kaydediyoruz.
df.to_sql('sepetler',conn,if_exists='replace',index=True)
print("veri tabanı oluşturuldu ve veriler aktarıldı")

veri tabanı oluşturuldu ve veriler aktarıldı

In [1]:
import pandas as pd
import sqlite3